PcHelpCentralApp/Areas/Admin/Controllers/UserController.cs
using Entities.Dtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;
using System.Data;

namespace PcHelpCentralApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly IServiceManager _manager;

        public UserController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var users = _manager.AuthService.GetAllUsers();
            return View(users);
        }

        public IActionResult Create()
        {
            return View(new UserDtoForCreation()
            {
                Roles = new HashSet<string>(_manager
                    .AuthService
                    .Roles
                    .Select(r => r.Name)
                    .ToList())
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] UserDtoForCreation userDto)
        {
            var result = await _manager.AuthService.CreateUser(userDto);
            return result.Succeeded
                ? RedirectToAction("Index")
                : View();
        }

        public async Task<IActionResult> Update([FromRoute(Name = "id")] string id)
        {
            var user = await _manager.AuthService.GetOneUserForUpdate(id);
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([FromForm] UserDtoForUpdate userDto)
        {
            if (ModelState.IsValid)
            {
                await _manager.AuthService.Update(userDto);
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> ResetPassword([FromRoute(Name = "id")] string id)
        {
            return View(new ResetPasswordDto()
            {
                UserName = id
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ResetPassword([FromForm] ResetPasswordDto model)
        {
            var result = await _manager.AuthService.ResetPassword(model);
            return result.Succeeded
                ? RedirectToAction("Index")
                : View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteOneUser([FromForm] UserDto userDto)
        {
            var result = await _manager
                .AuthService
                .DeleteOneUser(userDto.UserName);

            return result.Succeeded
                ? RedirectToAction("Index")
                : View();
        }
    }
}

PcHelpCentralApp/Components/SolutionSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Services.Contracts;

namespace PcHelpCentralApp.Components
{
    public class SolutionSummaryViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public SolutionSummaryViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public string Invoke()
        {
            return _manager.SolutionService.GetAllSolutions(false).Count().ToString();
        }
    }
}

PcHelpCentralApp/Controllers/SolutionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Entities.Models;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;
using Entities.RequestParameters;
using PcHelpCentralApp.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Entities.Dtos;
using Microsoft.AspNetCore.Identity;

namespace PcHelpCentralApp.Controllers
{

    public class SolutionController : Controller
    {
        private readonly IServiceManager _manager;

        public SolutionController(IServiceManager manager)
        {
            _manager = manager;
        }


        public IActionResult Index(SolutionRequestParameters p)
        {
            ViewData["Title"] = "Solutions to problems.";

            var solutions = _manager.SolutionService.GetAllSolutionsWithDetails(p);
            var pagination = new Pagination()
            {
                CurrentPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItems = _manager.SolutionService.GetAllSolutions(false).Count()
            };
            return View(new SolutionListViewModel()
            {
              Solutions = solutions,
              Pagination = pagination
            });

        }

        public IActionResult Get([FromRoute(Name = "id")] int id)
        {
            var model = _manager.SolutionService.GetOneSolution(id, false);
            ViewData["Title"] = model?.SolutionText;
            return View(model);
        }


    }
}

PcHelpCentralApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manager - @ViewData["Title"]</title>
    <link rel="stylesheet" asp-asp-append-version="true" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" asp-asp-append-version="true" href="~/css/site.css" />
    <link rel="stylesheet" asp-asp-append-version="true" href="~/lib/font-awesome/css/all.css" />
    <script src="https://cdn.tiny.cloud/1/it9v0gkc395v7r4jq7nqldn24a6sqaq0z5wkon9rn8to0z4q/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: 'textarea#tiny',
            plugins: [
                'a11ychecker', 'advlist', 'advcode', 'advtable', 'autolink', 'checklist', 'export',
                'lists', 'link', 'image', 'charmap', 'preview', 'anchor', 'searchreplace', 'visualblocks',
                'powerpaste', 'fullscreen', 'formatpainter', 'insertdatetime', 'media', 'table', 'help', 'wordcount'
            ],
            toolbar: 'undo redo | a11ycheck casechange blocks | bold italic backcolor | alignleft aligncenter alignright alignjustify |' +
                'bullist numlist checklist outdent indent | removeformat | code table help'
        })
    </script>

</head>

<body>
    <header>
        <partial name="_Navbar" />
        @RenderSection("Header",false)
    </header>
    <div class="container">
        <div>
            <partial name="_Notification" />
        </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    @await RenderSectionAsync("Scripts",required:false)
</body>

</html>

PcHelpCentralApp/Areas/Admin/Views/Shared/_Navbar.cshtml
<nav class="navbar bg-dark border-bottom navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand text-white" href="/">Admin</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNavAltMarkup">

            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-white" aria-current="page" asp-controller="Solution" asp-action="Get">Solutions (@await Component.InvokeAsync("SolutionSummary"))</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" aria-current="page" asp-controller="User" asp-action="Index">Users</a>
                </li>
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a target="_blank" class="nav-link text-white" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">
                        <i class="fa fa-solid fa search"></i>
                        Web</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" aria-current="page" asp-area="" asp-controller="Account" asp-action="Logout">
                        <i class="fa-solid fa-right-from-bracket"></i>
                        Log out</a>
                </li>
            </ul>
        </div>
    
    
    </div>
</nav>