PcHelpCentralApp/Components/SolutionFilterMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace PcHelpCentralApp.Components
{
    public class SolutionFilterMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

PcHelpCentralApp/Controllers/HomeController.cs
using PcHelpCentralApp.Models;
using Entities.Dtos;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Entities.RequestParameters;
using Services.Contracts;

namespace PcHelpCentralApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly IServiceManager _manager;

        public HomeController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index(SolutionRequestParameters p)
        {
            ViewData["Title"] = "Search for your problem.";

            var solutions = _manager.SolutionService.GetAllSolutionsInTrends(p, false);
            var pagination = new Pagination()
            {
                CurrentPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItems = _manager.SolutionService.GetShowCaseSolutions(false).Count()
            };
            return View(new SolutionListViewModel()
            {
                Solutions = solutions,
                Pagination = pagination
            });
        }

        public IActionResult Get(SolutionRequestParameters p)
        {
            var solutions = _manager.SolutionService.GetAllSolutionsWithDetails(p);
            var pagination = new Pagination()
            {
                CurrentPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItems = _manager.SolutionService.GetAllSolutions(false).Count()
            };
            return View(new SolutionListViewModel()
            {
                Solutions = solutions,
                Pagination = pagination
            });
        }
       
    }
}

PcHelpCentralApp/Views/Home/Get.cshtml
@model SolutionListViewModel


<div class="text-center">
    @await Component.InvokeAsync("SolutionFilterMenu")
</div>

<div>
    <partial name="_SolutionTable" />
</div>

PcHelpCentralApp/Views/Home/Index.cshtml
<div>
     <div class="text-center">
         @await Component.InvokeAsync("SolutionFilterMenu")
     </div>
</div>


<div class="row mt-5">
    <div class="text-center">
        <h2 style="font-family: 'Poppins', sans-serif; color: #ffffff;">Trends</h2>
    </div>
    @foreach (var prd in Model.Solutions)
    {
        <partial name="_ProductCard" model="prd" />
    }
</div>

<div class="text-center">
    <div page-model="@Model?.Pagination" page-action="Index" page-classes-enabled="true" page-class="btn"
         page-class-normal="btn-outline-dark" page-class-selected="btn-secondary" class="btn-group">
    </div>
</div>